version: "3.8"

services:
  database:
      image: postgres:14
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_HOST_AUTH_METHOD: trust
      ports:
        - 5432:5432
      volumes:
        - volume-postgres:/var/lib/postgresql/data
      restart: unless-stopped
      # command: -p 5432

  app:
    build:
      dockerfile: Dockerfile
      context: .
    working_dir: /app
    command: ./balance-app
    stdin_open: true
    depends_on:
      - database
    links:
      - database
    environment:
      - SERVICES_PROFILE=docker
    ports:
      - 8080:8080
    env_file:
      - ./local.env


volumes:
  volume-postgres:

